// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var C$AgdaMode = require("./C.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Util$AgdaMode = require("./Util.bs.js");
var Range$AgdaMode = require("./Range.bs.js");
var Concrete$AgdaMode = require("./Concrete.bs.js");

var component = ReasonReact.statelessComponent("TypeError");

function make(typeError, emacsMessage, _) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function () {
                console.log(emacsMessage);
                switch (typeError.tag | 0) {
                  case 0 : 
                      return React.createElement("div", undefined, typeError[0]);
                  case 1 : 
                      return React.createElement("div", undefined, "The target of a constructor must be the datatype applied to its parameters, ", ReasonReact.element(undefined, undefined, Concrete$AgdaMode.Expr[/* make */0](typeError[0], /* array */[])), " isn't");
                  case 2 : 
                      var dataOrRecord = typeError[2];
                      var type_ = dataOrRecord !== undefined ? (
                          dataOrRecord ? "(record) " : "(datatype) "
                        ) : "";
                      return React.createElement("div", undefined, "Duplicate definition of module ", ReasonReact.element(undefined, undefined, C$AgdaMode.Name[/* make */4](typeError[1], /* array */[])), React.createElement("br", undefined), "Previous definition of " + (type_ + "module "), ReasonReact.element(undefined, undefined, C$AgdaMode.QName[/* make */2](typeError[0], /* array */[])));
                  case 3 : 
                      return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Concrete$AgdaMode.Expr[/* make */0](typeError[0], /* array */[])), " should be a function type, but it isn't");
                  case 4 : 
                      return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Concrete$AgdaMode.Expr[/* make */0](typeError[0], /* array */[])), " should be a sort, but it isn't");
                  case 5 : 
                      return React.createElement("div", undefined, "expected : ", ReasonReact.element(undefined, undefined, Concrete$AgdaMode.Expr[/* make */0](typeError[2], /* array */[])), React.createElement("br", undefined), "  actual : ", ReasonReact.element(undefined, undefined, Concrete$AgdaMode.Expr[/* make */0](typeError[1], /* array */[])), React.createElement("br", undefined), " of type : ", ReasonReact.element(undefined, undefined, Concrete$AgdaMode.Expr[/* make */0](typeError[3], /* array */[])), React.createElement("br", undefined));
                  case 6 : 
                      return React.createElement("div", undefined, "Multiple definitions of ", ReasonReact.element(undefined, undefined, C$AgdaMode.QName[/* make */2](typeError[0], /* array */[])), React.createElement("br", undefined), "Previous definition at ", ReasonReact.element(undefined, undefined, Range$AgdaMode.make(typeError[1], undefined, /* array */[])));
                  case 7 : 
                      return React.createElement("div", undefined, "The right-hand side can only be omitted if there is an absurd pattern, () or {}, in the left-hand side.");
                  case 8 : 
                      var forgetSpaceColon = function (name) {
                        var __x = C$AgdaMode.QName[/* toString */0](name);
                        return $$String.contains(__x, /* ":" */58);
                      };
                      var forgetSpaceArrow = function (name) {
                        var __x = C$AgdaMode.QName[/* toString */0](name);
                        return Curry._2(Util$AgdaMode.contains, __x, "->");
                      };
                      var pair = function (param) {
                        var suggestions = param[1];
                        var name = param[0];
                        var colon = forgetSpaceColon(name);
                        var arrow = forgetSpaceArrow(name);
                        var hasSuggestions = List.length(suggestions) !== 0;
                        var shouldRender = colon || arrow || hasSuggestions;
                        return React.createElement("li", undefined, ReasonReact.element(undefined, undefined, C$AgdaMode.QName[/* make */2](name, /* array */[])), " is not in scope", shouldRender ? React.createElement("p", undefined, colon ? React.createElement(React.Fragment, undefined, "did you forget space around the ':'?") : null, arrow ? React.createElement(React.Fragment, undefined, "did you forget space around the '->'?") : null, hasSuggestions ? React.createElement(React.Fragment, undefined, "did you mean ", Util$AgdaMode.sepBy(" or ", List.map((function (value) {
                                                          return ReasonReact.element(undefined, undefined, C$AgdaMode.QName[/* make */2](value, /* array */[]));
                                                        }), suggestions)), " ?") : null) : null);
                      };
                      return ReactDOMRe.createElementVariadic("ul", undefined, $$Array.of_list(List.map(pair, typeError[0])));
                  case 9 : 
                      return React.createElement("div", undefined, JSON.stringify(typeError[0]));
                  
                }
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
