// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var AgdaMode = /* module */Block.localModule([], []);

var TypeCheckingPositivity = /* module */Block.localModule([], []);

var Position = /* module */Block.localModule([], []);

var Parser = /* module */Block.localModule([], []);

var CommonPrim = /* module */Block.localModule([], []);

var Notation = /* module */Block.localModule([], []);

var Fixity = /* module */Block.localModule([], []);

var C = /* module */Block.localModule([], []);

var A = /* module */Block.localModule([], []);

var Scope = /* module */Block.localModule([], []);

var Info = /* module */Block.localModule([], []);

var Literal = /* module */Block.localModule([], []);

var Concrete = /* module */Block.localModule([], []);

var Common = /* module */Block.localModule([], []);

var Syntax = /* module */Block.localModule([
    "Position",
    "Parser",
    "CommonPrim",
    "Notation",
    "Fixity",
    "C",
    "A",
    "Scope",
    "Info",
    "Literal",
    "Concrete",
    "Common"
  ], [
    Position,
    Parser,
    CommonPrim,
    Notation,
    Fixity,
    C,
    A,
    Scope,
    Info,
    Literal,
    Concrete,
    Common
  ]);

var TypeChecking = /* module */Block.localModule([], []);

var Interaction = /* module */Block.localModule([], []);

exports.AgdaMode = AgdaMode;
exports.TypeCheckingPositivity = TypeCheckingPositivity;
exports.Syntax = Syntax;
exports.TypeChecking = TypeChecking;
exports.Interaction = Interaction;
/* No side effect */
