// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Syntax__Name$AgdaMode = require("./Syntax__Name.bs.js");

var NamePart = Syntax__Name$AgdaMode.NamePart;

var Name = Syntax__Name$AgdaMode.Name;

var QName = Syntax__Name$AgdaMode.QName;

var BoundName = Syntax__Name$AgdaMode.BoundName;

var CommonPrim = 0;

var Concrete = 0;

var Literal = 0;

var Range = 0;

exports.NamePart = NamePart;
exports.Name = Name;
exports.QName = QName;
exports.BoundName = BoundName;
exports.CommonPrim = CommonPrim;
exports.Concrete = Concrete;
exports.Literal = Literal;
exports.Range = Range;
/* Syntax__Name-AgdaMode Not a pure module */
