// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Error$AgdaMode = require("./Error.bs.js");
var Context$AgdaMode = require("../Context.bs.js");
var Decoder$AgdaMode = require("../../Decoder.bs.js");
var AllGoalsWarnings$AgdaMode = require("./AllGoalsWarnings.bs.js");

var component = ReasonReact.statelessComponent("JSONBody");

function make(raw, emit, _) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function () {
                var match = Decoder$AgdaMode.parseBody(raw);
                var tmp;
                switch (match.tag | 0) {
                  case 0 : 
                      tmp = ReasonReact.element(undefined, undefined, AllGoalsWarnings$AgdaMode.make(match[0], /* array */[]));
                      break;
                  case 1 : 
                      tmp = ReasonReact.element(undefined, undefined, Error$AgdaMode.make(match[0], match[1], /* array */[]));
                      break;
                  case 2 : 
                      tmp = React.createElement("p", undefined, match[0]);
                      break;
                  
                }
                return ReasonReact.element(undefined, undefined, Curry._2(Context$AgdaMode.Emitter[/* Provider */1][/* make */0], emit, /* array */[React.createElement("section", {
                                      className: "agda-body"
                                    }, tmp)]));
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.raw, jsProps.emit, /* array */[]);
      }));

exports.component = component;
exports.make = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
