// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Util$AgdaMode = require("../../Util.bs.js");
var Async$AgdaMode = require("../../Util/Async.bs.js");
var Event$AgdaMode = require("../../Util/Event.bs.js");
var MiniEditor$AgdaMode = require("../MiniEditor.bs.js");
var Settings__Connection__Error$AgdaMode = require("./Settings__Connection__Error.bs.js");

function initialState(param) {
  return /* record */Block.record([
            "connected",
            "editorRef",
            "editorModel",
            "error",
            "value"
          ], [
            false,
            Block.record(["contents"], [undefined]),
            Block.record(["contents"], [MiniEditor$AgdaMode.Model[/* make */0](/* () */0)]),
            undefined,
            ""
          ]);
}

function reducer(action, state) {
  if (typeof action === "number") {
    return /* NoUpdate */0;
  } else {
    return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
              /* record */Block.record([
                  "connected",
                  "editorRef",
                  "editorModel",
                  "error",
                  "value"
                ], [
                  state[/* connected */0],
                  state[/* editorRef */1],
                  state[/* editorModel */2],
                  action[0],
                  action[1]
                ]),
              (function (_self) {
                  return Rebase.Option[/* forEach */8]((function (editor) {
                                atom.views.getView(editor).focus();
                                editor.selectAll();
                                return /* () */0;
                              }), state[/* editorRef */1][0]);
                })
            ]);
  }
}

var component = ReasonReact.reducerComponent("Connection");

function setEditorRef(theRef, param) {
  param[/* state */1][/* editorRef */1][0] = Caml_option.some(theRef);
  return /* () */0;
}

function make(inquireConnection, onInquireConnection, connection, hidden, _children) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            (function (self) {
                return Event$AgdaMode.destroyWhen(self[/* onUnmount */4], Event$AgdaMode.onOk((function (param) {
                                    Curry._1(self[/* send */3], /* Inquire */Block.simpleVariant("Inquire", [
                                            param[0],
                                            param[1]
                                          ]));
                                    return Async$AgdaMode.finalOk((function (value) {
                                                  return Event$AgdaMode.emitOk(value, onInquireConnection);
                                                }), MiniEditor$AgdaMode.Model[/* inquire */1](self[/* state */1][/* editorModel */2][0]));
                                  }))(inquireConnection));
              }),
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function (self) {
                var connected = Rebase.Option[/* isSome */13](connection);
                var className = Curry._1(Util$AgdaMode.ClassName[/* serialize */2], Util$AgdaMode.ClassName[/* addWhen */1]("inquiring", !connected, Util$AgdaMode.ClassName[/* addWhen */1]("hidden", hidden, /* :: */Block.simpleVariant("::", [
                                "agda-settings-connection",
                                /* [] */0
                              ]))));
                var match = self[/* state */1];
                var tmp;
                if (connection !== undefined) {
                  var conn = connection;
                  var match$1 = conn[/* metadata */0][/* protocol */3];
                  tmp = React.createElement(React.Fragment, undefined, React.createElement("p", undefined, "Connection: established"), React.createElement("p", undefined, "Path: " + conn[/* metadata */0][/* path */0]), React.createElement("p", undefined, "Version: " + conn[/* metadata */0][/* version */2]), React.createElement("p", undefined, "Supported protocol: " + (
                            match$1 ? "Emacs / JSON" : "Emacs"
                          )));
                } else {
                  tmp = React.createElement(React.Fragment, undefined, React.createElement("p", undefined, "Connection: not established"), React.createElement("p", undefined, "Path: unknown"), React.createElement("p", undefined, "Version: unknown"), React.createElement("p", undefined, "Supported protocol: unknown"));
                }
                return React.createElement("section", {
                            className: className
                          }, React.createElement("form", undefined, React.createElement("ul", {
                                    className: "agda-settings-connection-dashboard"
                                  }, React.createElement("li", {
                                        id: "agda-settings-connection-agda"
                                      }, React.createElement("h2", undefined, React.createElement("label", {
                                                className: "input-label"
                                              }, React.createElement("span", undefined, "Connection to Agda"), React.createElement("input", {
                                                    className: "input-toggle",
                                                    checked: connected,
                                                    type: "checkbox",
                                                    onChange: (function (param) {
                                                        return /* () */0;
                                                      })
                                                  }))), React.createElement("div", undefined, tmp, React.createElement("p", undefined, ReasonReact.element(undefined, undefined, MiniEditor$AgdaMode.make(connection !== undefined ? connection[/* metadata */0][/* path */0] : self[/* state */1][/* value */4], "path to Agda", false, undefined, (function (result) {
                                                          return MiniEditor$AgdaMode.Model[/* answer */2](result, self[/* state */1][/* editorModel */2][0]);
                                                        }), Caml_option.some((function () {
                                                              return /* () */0;
                                                            })), undefined, undefined, Curry._1(self[/* handle */0], setEditorRef), /* array */[]))), React.createElement("p", undefined, React.createElement("button", {
                                                    className: "btn icon icon-search inline-block-tight",
                                                    onClick: (function (param) {
                                                        return /* () */0;
                                                      })
                                                  }, "auto search")), connected ? null : ReasonReact.element(undefined, undefined, Settings__Connection__Error$AgdaMode.make(match[/* error */3], /* array */[])))))));
              }),
            initialState,
            component[/* retainedProps */11],
            reducer,
            component[/* jsElementWrapped */13]
          ]);
}

exports.initialState = initialState;
exports.reducer = reducer;
exports.component = component;
exports.setEditorRef = setEditorRef;
exports.make = make;
/* component Not a pure module */
