// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");
var Type__Location$AgdaMode = require("../Type/Type__Location.bs.js");
var Component__Link$AgdaMode = require("./Component__Link.bs.js");

function Component__Range(Props) {
  var range = Props.range;
  var match = Props.abbr;
  var abbr = match !== undefined ? match : false;
  if (abbr) {
    return React.createElement(Component__Link$AgdaMode.make, {
                target: /* RangeLink */Caml_chrome_debugger.variant("RangeLink", 0, [range]),
                jump: true,
                children: React.createElement("span", {
                      className: "text-subtle range icon icon-link"
                    })
              });
  } else {
    return React.createElement(Component__Link$AgdaMode.make, {
                target: /* RangeLink */Caml_chrome_debugger.variant("RangeLink", 0, [range]),
                jump: true,
                children: React.createElement("span", {
                      className: "text-subtle range icon icon-link"
                    }, Type__Location$AgdaMode.$$Range.toString(range))
              });
  }
}

var Link = 0;

var make = Component__Range;

exports.Link = Link;
exports.make = make;
/* react Not a pure module */
