// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Resource$AgdaMode = require("./Resource.bs.js");

function send(input, channel) {
  return $$Promise.flatMap(Curry._1(channel.acquire, /* () */0), (function (trigger) {
                return Curry._1(trigger, input);
              }));
}

function sendTo(channel, input) {
  return $$Promise.flatMap(Curry._1(channel.acquire, /* () */0), (function (trigger) {
                return Curry._1(trigger, input);
              }));
}

function recv(callback, channel) {
  return Curry._1(channel.supply, callback);
}

var make = Resource$AgdaMode.make;

exports.make = make;
exports.send = send;
exports.sendTo = sendTo;
exports.recv = recv;
/* Promise Not a pure module */
