// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function make(param) {
  var resource = /* record */Caml_chrome_debugger.record(["contents"], [undefined]);
  var queue = /* record */Caml_chrome_debugger.record(["contents"], [0]);
  var acquire = function (param) {
    var match = resource[0];
    if (match !== undefined) {
      return $$Promise.resolved(Caml_option.valFromOption(match));
    } else {
      var match$1 = $$Promise.pending(/* () */0);
      queue[0] = /* :: */Caml_chrome_debugger.simpleVariant("::", [
          match$1[1],
          queue[0]
        ]);
      return match$1[0];
    }
  };
  var supply = function (x) {
    resource[0] = Caml_option.some(x);
    return Rebase.List.forEach((function (resolve) {
                  return Curry._1(resolve, x);
                }), queue[0]);
  };
  return /* record */Caml_chrome_debugger.record([
            "acquire",
            "supply"
          ], [
            acquire,
            supply
          ]);
}

exports.make = make;
/* Promise Not a pure module */
