// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Emacs$AgdaMode = require("../../../Emacs.bs.js");
var Context$AgdaMode = require("../../Context.bs.js");
var EmacsMeta$AgdaMode = require("./EmacsMeta.bs.js");

var component = ReasonReact.statelessComponent("EmacsGoalTypeContext");

function make(goalTypeContext, emit, _) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function () {
                var parsed = Emacs$AgdaMode.Parser[/* goalTypeContext */10](goalTypeContext);
                console.log(parsed[/* metas */2]);
                return ReasonReact.element(undefined, undefined, Curry._2(Context$AgdaMode.Emitter[/* Provider */1][/* make */0], emit, /* array */[React.createElement("section", {
                                      className: "metas"
                                    }, ReactDOMRe.createElementVariadic("ul", undefined, $$Array.map((function (meta) {
                                                return ReasonReact.element(undefined, undefined, EmacsMeta$AgdaMode.make(meta, /* array */[]));
                                              }), parsed[/* metas */2])))]));
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.goalTypeContext, jsProps.emit, /* array */[]);
      }));

exports.component = component;
exports.make = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
