// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");

function userInput(s) {
  var s$1 = s.replace((/\\/g), "\\\\").replace((/\"/g), "\\\"").replace((/\n/g), "\\n");
  var match = atom.config.get("agda-mode.trimSpaces");
  if (match) {
    return Rebase.$$String[/* trim */8](s$1);
  } else {
    return s$1;
  }
}

exports.userInput = userInput;
/* No side effect */
