// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDom = require("react-dom");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Tab$AgdaMode = require("./View/Tab.bs.js");
var Util$AgdaMode = require("./Util.bs.js");
var Panel$AgdaMode = require("./View/Panel/Panel.bs.js");
var Editor$AgdaMode = require("./Editor.bs.js");

function hook(f, handle) {
  f[0] = handle;
  return /* () */0;
}

function make(param) {
  var updateHeader = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var updateRawBody = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var updateMode = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var updateActivation = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var updateMountTo = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var inquireQuery = /* record */Block.record(["contents"], [(function (param, param$1) {
          return Promise.reject(Util$AgdaMode.TelePromise[/* Uninitialized */0]);
        })]);
  var interceptAndInsertKey = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var activateInputMethod = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  var activateSettingsView = /* record */Block.record(["contents"], [(function (param) {
          return /* () */0;
        })]);
  return /* record */Block.record([
            "updateHeader",
            "updateRawBody",
            "updateMode",
            "updateMountTo",
            "updateActivation",
            "inquireQuery",
            "interceptAndInsertKey",
            "activateInputMethod",
            "activateSettingsView"
          ], [
            updateHeader,
            updateRawBody,
            updateMode,
            updateMountTo,
            updateActivation,
            inquireQuery,
            interceptAndInsertKey,
            activateInputMethod,
            activateSettingsView
          ]);
}

var Handles = /* module */Block.localModule([
    "hook",
    "make"
  ], [
    hook,
    make
  ]);

function createElement(param) {
  var element = document.createElement("article");
  element.classList.add("agda-mode");
  atom.workspace.addBottomPanel({
        item: element,
        visible: true
      });
  return element;
}

function initialState(editor, param) {
  return /* record */Block.record([
            "header",
            "body",
            "mountAt",
            "activated",
            "settingsView",
            "editor",
            "mode"
          ], [
            Block.record([
                "text",
                "style"
              ], [
                "",
                ""
              ]),
            Block.record([
                "maxHeight",
                "raw"
              ], [
                170,
                0
              ]),
            Block.variant("Bottom", 0, [createElement(/* () */0)]),
            false,
            undefined,
            Editor$AgdaMode.make(editor),
            0
          ]);
}

function mountPanel(self, mountTo) {
  var createTab = function (param) {
    return Tab$AgdaMode.make(self[/* state */1][/* editor */5][/* source */1], (function (param, param$1, previousItem) {
                  var pane = atom.workspace.paneForItem(previousItem);
                  pane.activate();
                  pane.activateItem(previousItem);
                  return /* () */0;
                }), undefined, (function (param) {
                  return Curry._1(self[/* send */3], /* MountTo */Block.variant("MountTo", 8, [/* ToBottom */0]));
                }), undefined, /* () */0);
  };
  var match = self[/* state */1][/* mountAt */2];
  if (match.tag) {
    if (mountTo) {
      return /* () */0;
    } else {
      Curry._1(match[0][/* kill */1], /* () */0);
      return Curry._1(self[/* send */3], /* UpdateMountAt */Block.variant("UpdateMountAt", 4, [/* Bottom */Block.variant("Bottom", 0, [createElement(/* () */0)])]));
    }
  } else if (mountTo) {
    return Curry._1(self[/* send */3], /* UpdateMountAt */Block.variant("UpdateMountAt", 4, [/* Pane */Block.variant("Pane", 1, [createTab(/* () */0)])]));
  } else {
    return /* () */0;
  }
}

function reducer(handles, action, state) {
  if (typeof action === "number") {
    switch (action) {
      case 0 : 
          var init = state[/* editor */5];
          return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                    /* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        Block.record([
                            "focused",
                            "source",
                            "query"
                          ], [
                            1,
                            init[/* source */1],
                            init[/* query */2]
                          ]),
                        state[/* mode */6]
                      ]),
                    (function (self) {
                        return Editor$AgdaMode.Focus[/* onQuery */2](self[/* state */1][/* editor */5]);
                      })
                  ]);
      case 1 : 
          var init$1 = state[/* editor */5];
          return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                    /* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        Block.record([
                            "focused",
                            "source",
                            "query"
                          ], [
                            0,
                            init$1[/* source */1],
                            init$1[/* query */2]
                          ]),
                        state[/* mode */6]
                      ]),
                    (function (self) {
                        return Editor$AgdaMode.Focus[/* onSource */1](self[/* state */1][/* editor */5]);
                      })
                  ]);
      case 2 : 
          var match = state[/* mountAt */2];
          if (match.tag) {
            var tab = match[0];
            return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                      /* record */Block.record([
                          "header",
                          "body",
                          "mountAt",
                          "activated",
                          "settingsView",
                          "editor",
                          "mode"
                        ], [
                          state[/* header */0],
                          state[/* body */1],
                          state[/* mountAt */2],
                          true,
                          state[/* settingsView */4],
                          state[/* editor */5],
                          state[/* mode */6]
                        ]),
                      (function (param) {
                          return Curry._1(tab[/* activate */2], /* () */0);
                        })
                    ]);
          } else {
            return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                          "header",
                          "body",
                          "mountAt",
                          "activated",
                          "settingsView",
                          "editor",
                          "mode"
                        ], [
                          state[/* header */0],
                          state[/* body */1],
                          state[/* mountAt */2],
                          true,
                          state[/* settingsView */4],
                          state[/* editor */5],
                          state[/* mode */6]
                        ])]);
          }
      case 3 : 
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        false,
                        state[/* settingsView */4],
                        state[/* editor */5],
                        state[/* mode */6]
                      ])]);
      
    }
  } else {
    switch (action.tag | 0) {
      case 0 : 
          var init$2 = state[/* editor */5];
          var init$3 = state[/* editor */5][/* query */2];
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        Block.record([
                            "focused",
                            "source",
                            "query"
                          ], [
                            init$2[/* focused */0],
                            init$2[/* source */1],
                            Block.record([
                                "value",
                                "placeholder",
                                "ref",
                                "telePromise"
                              ], [
                                init$3[/* value */0],
                                init$3[/* placeholder */1],
                                Caml_option.some(action[0]),
                                init$3[/* telePromise */3]
                              ])
                          ]),
                        state[/* mode */6]
                      ])]);
      case 1 : 
          var init$4 = state[/* editor */5];
          var init$5 = state[/* editor */5][/* query */2];
          return /* UpdateWithSideEffects */Block.variant("UpdateWithSideEffects", 2, [
                    /* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        Block.record([
                            "focused",
                            "source",
                            "query"
                          ], [
                            init$4[/* focused */0],
                            init$4[/* source */1],
                            Block.record([
                                "value",
                                "placeholder",
                                "ref",
                                "telePromise"
                              ], [
                                action[1],
                                action[0],
                                init$5[/* ref */2],
                                init$5[/* telePromise */3]
                              ])
                          ]),
                        state[/* mode */6]
                      ]),
                    (function (self) {
                        return Editor$AgdaMode.Focus[/* onQuery */2](self[/* state */1][/* editor */5]);
                      })
                  ]);
      case 2 : 
          var open_ = action[0];
          return /* SideEffects */Block.variant("SideEffects", 1, [(function (self) {
                        var match = state[/* settingsView */4];
                        if (match !== undefined) {
                          if (open_) {
                            return 0;
                          } else {
                            Curry._1(match[/* kill */1], /* () */0);
                            return Curry._1(self[/* send */3], /* UpdateSettingsView */Block.variant("UpdateSettingsView", 3, [undefined]));
                          }
                        } else if (open_) {
                          var tab = Tab$AgdaMode.make(self[/* state */1][/* editor */5][/* source */1], undefined, undefined, (function (param) {
                                  Curry._1(self[/* send */3], /* ToggleSettingsTab */Block.variant("ToggleSettingsTab", 2, [false]));
                                  return Curry._1(handles[/* activateSettingsView */8][0], false);
                                }), undefined, /* () */0);
                          return Curry._1(self[/* send */3], /* UpdateSettingsView */Block.variant("UpdateSettingsView", 3, [tab]));
                        } else {
                          return 0;
                        }
                      })]);
      case 3 : 
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        action[0],
                        state[/* editor */5],
                        state[/* mode */6]
                      ])]);
      case 4 : 
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        action[0],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        state[/* editor */5],
                        state[/* mode */6]
                      ])]);
      case 5 : 
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        action[0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        state[/* editor */5],
                        state[/* mode */6]
                      ])]);
      case 6 : 
          var init$6 = state[/* body */1];
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        Block.record([
                            "maxHeight",
                            "raw"
                          ], [
                            init$6[/* maxHeight */0],
                            action[0]
                          ]),
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        state[/* editor */5],
                        state[/* mode */6]
                      ])]);
      case 7 : 
          return /* Update */Block.variant("Update", 0, [/* record */Block.record([
                        "header",
                        "body",
                        "mountAt",
                        "activated",
                        "settingsView",
                        "editor",
                        "mode"
                      ], [
                        state[/* header */0],
                        state[/* body */1],
                        state[/* mountAt */2],
                        state[/* activated */3],
                        state[/* settingsView */4],
                        state[/* editor */5],
                        action[0]
                      ])]);
      case 8 : 
          var mountTo = action[0];
          return /* SideEffects */Block.variant("SideEffects", 1, [(function (self) {
                        return mountPanel(self, mountTo);
                      })]);
      
    }
  }
}

var component = ReasonReact.reducerComponent("View");

function make$1(editor, handles, _children) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            (function (self) {
                handles[/* updateMountTo */3][0] = (function (mountTo) {
                    return Curry._1(self[/* send */3], /* MountTo */Block.variant("MountTo", 8, [mountTo]));
                  });
                handles[/* updateMode */2][0] = (function (mode) {
                    return Curry._1(self[/* send */3], /* UpdateMode */Block.variant("UpdateMode", 7, [mode]));
                  });
                handles[/* updateActivation */4][0] = (function (activate) {
                    return Curry._1(self[/* send */3], activate ? /* Activate */2 : /* Deactivate */3);
                  });
                handles[/* updateHeader */0][0] = (function (header) {
                    return Curry._1(self[/* send */3], /* UpdateHeader */Block.variant("UpdateHeader", 5, [header]));
                  });
                handles[/* updateRawBody */1][0] = (function (rawBody) {
                    return Curry._1(self[/* send */3], /* UpdateRawBody */Block.variant("UpdateRawBody", 6, [rawBody]));
                  });
                handles[/* inquireQuery */5][0] = (function (placeholder, value) {
                    Curry._1(self[/* send */3], /* InquireQuery */Block.variant("InquireQuery", 1, [
                            placeholder,
                            value
                          ]));
                    var promise = Util$AgdaMode.TelePromise[/* make */2](/* () */0);
                    Curry._2(self[/* handle */0], (function (param, newSelf) {
                            Editor$AgdaMode.Query[/* inquire */0](newSelf[/* state */1][/* editor */5]).then((function (answer) {
                                      return Promise.resolve(Curry._1(promise[/* resolve */1], answer));
                                    })).catch((function (error) {
                                    return Promise.resolve(Curry._1(promise[/* reject */2], [
                                                    Util$AgdaMode.JSPromiseError,
                                                    error
                                                  ]));
                                  }));
                            return /* () */0;
                          }), /* () */0);
                    return Curry._1(promise[/* wire */0], /* () */0);
                  });
                return /* () */0;
              }),
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function (self) {
                var match = self[/* state */1];
                var editor = match[/* editor */5];
                var mountAt = match[/* mountAt */2];
                var element;
                element = mountAt.tag ? Caml_option.some(mountAt[0][/* element */0]) : Caml_option.some(mountAt[0]);
                var hidden;
                hidden = mountAt.tag ? false : !match[/* activated */3];
                var partial_arg = handles[/* interceptAndInsertKey */6];
                var partial_arg$1 = handles[/* activateInputMethod */7];
                var partial_arg$2 = handles[/* activateSettingsView */8];
                return React.createElement(React.Fragment, undefined, ReasonReact.element(undefined, undefined, Panel$AgdaMode.make(editor, element, (function (mountTo) {
                                      return Curry._1(self[/* send */3], /* MountTo */Block.variant("MountTo", 8, [mountTo]));
                                    }), match[/* body */1], match[/* header */0], mountAt, match[/* mode */6], hidden, (function (result) {
                                      Curry._1(Editor$AgdaMode.Query[/* answer */1](editor), result);
                                      Curry._1(handles[/* activateInputMethod */7][0], false);
                                      Curry._1(self[/* send */3], /* FocusSource */1);
                                      return Curry._1(self[/* send */3], /* UpdateMode */Block.variant("UpdateMode", 7, [/* Display */0]));
                                    }), (function (focused) {
                                      return Curry._1(self[/* send */3], focused ? /* FocusQuery */0 : /* FocusSource */1);
                                    }), (function () {
                                      Curry._1(Editor$AgdaMode.Query[/* reject */2](editor), Editor$AgdaMode.QueryCancelled);
                                      Curry._1(handles[/* activateInputMethod */7][0], false);
                                      Curry._1(self[/* send */3], /* FocusSource */1);
                                      return Curry._1(self[/* send */3], /* UpdateMode */Block.variant("UpdateMode", 7, [/* Display */0]));
                                    }), (function (ref) {
                                      return Curry._1(self[/* send */3], /* SetGeneralRef */Block.variant("SetGeneralRef", 0, [ref]));
                                    }), editor[/* query */2][/* placeholder */1], editor[/* query */2][/* value */0], (function (param) {
                                      partial_arg[0] = param;
                                      return /* () */0;
                                    }), (function (param) {
                                      partial_arg$1[0] = param;
                                      return /* () */0;
                                    }), (function (param) {
                                      partial_arg$2[0] = param;
                                      return /* () */0;
                                    }), (function (status) {
                                      return Curry._1(self[/* send */3], /* ToggleSettingsTab */Block.variant("ToggleSettingsTab", 2, [status]));
                                    }), /* array */[])));
              }),
            (function (param) {
                return initialState(editor, param);
              }),
            component[/* retainedProps */11],
            (function (param, param$1) {
                return reducer(handles, param, param$1);
              }),
            component[/* jsElementWrapped */13]
          ]);
}

function initialize(editor) {
  var element = document.createElement("article");
  var handles = make(/* () */0);
  ReactDom.render(ReasonReact.element(undefined, undefined, make$1(editor, handles, /* array */[])), element);
  return handles;
}

exports.Handles = Handles;
exports.createElement = createElement;
exports.initialState = initialState;
exports.mountPanel = mountPanel;
exports.reducer = reducer;
exports.component = component;
exports.make = make$1;
exports.initialize = initialize;
/* component Not a pure module */
