// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Buffer$AgdaMode = require("../View/Panel/InputMethod/Buffer.bs.js");

var $$JSON = /* module */Block.localModule([], []);

var Header = /* module */Block.localModule([], []);

var emitter = React.createContext((function (_ev) {
        return /* () */0;
      }));

var make = emitter.Provider;

var Provider = /* module */Block.localModule(["make"], [make]);

var Mouse = /* module */Block.localModule([
    "emitter",
    "Provider"
  ], [
    emitter,
    Provider
  ]);

function reducer(state, action) {
  return /* record */Block.record(["inputMethod"], [action[0]]);
}

var initialState = /* record */Block.record(["inputMethod"], [Block.record([
        "activated",
        "markers",
        "buffer"
      ], [
        false,
        [],
        Buffer$AgdaMode.initial
      ])]);

var debugDispatch = React.createContext((function (param) {
        return /* () */0;
      }));

var make$1 = debugDispatch.Provider;

var Provider$1 = /* module */Block.localModule(["make"], [make$1]);

var Debug = /* module */Block.localModule([
    "reducer",
    "initialState",
    "debugDispatch",
    "Provider"
  ], [
    reducer,
    initialState,
    debugDispatch,
    Provider$1
  ]);

exports.$$JSON = $$JSON;
exports.Header = Header;
exports.Mouse = Mouse;
exports.Debug = Debug;
/* emitter Not a pure module */
