// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var TypeCheckingPositivity = /* module */Block.localModule([], []);

var Parser = /* module */Block.localModule([], []);

var CommonPrim = /* module */Block.localModule([], []);

var Notation = /* module */Block.localModule([], []);

var Fixity = /* module */Block.localModule([], []);

var Name = /* module */Block.localModule([], []);

var Literal = /* module */Block.localModule([], []);

var Concrete = /* module */Block.localModule([], []);

var Common = /* module */Block.localModule([], []);

exports.TypeCheckingPositivity = TypeCheckingPositivity;
exports.Parser = Parser;
exports.CommonPrim = CommonPrim;
exports.Notation = Notation;
exports.Fixity = Fixity;
exports.Name = Name;
exports.Literal = Literal;
exports.Concrete = Concrete;
exports.Common = Common;
/* No side effect */
