// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Type__Location$AgdaMode = require("../Type/Type__Location.bs.js");
var Component__Link$AgdaMode = require("./Component__Link.bs.js");

var component = ReasonReact.statelessComponent("Range");

function make(range, $staropt$star, _children) {
  var abbr = $staropt$star !== undefined ? $staropt$star : false;
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function (_self) {
                if (abbr) {
                  return ReasonReact.element(undefined, undefined, Component__Link$AgdaMode.make(range, true, undefined, undefined, /* array */[React.createElement("span", {
                                        className: "text-subtle range icon icon-link"
                                      })]));
                } else {
                  return ReasonReact.element(undefined, undefined, Component__Link$AgdaMode.make(range, true, undefined, undefined, /* array */[React.createElement("span", {
                                        className: "text-subtle range icon icon-link"
                                      }, Type__Location$AgdaMode.Range[/* toString */1](range))]));
                }
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.range, undefined, /* array */[]);
      }));

var Link = 0;

exports.component = component;
exports.Link = Link;
exports.make = make;
exports.jsComponent = jsComponent;
/* component Not a pure module */
