// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReactDom = require("react-dom");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Panel$AgdaMode = require("./Panel/Panel.bs.js");

var updateEmacsBody = /* record */Block.record(["contents"], [(function (param) {
        return /* () */0;
      })]);

var updateJSONBody = /* record */Block.record(["contents"], [(function (param) {
        return /* () */0;
      })]);

var updateHeader = /* record */Block.record(["contents"], [(function (param) {
        return /* () */0;
      })]);

function translateJSMountAt(jsMountAt) {
  switch (jsMountAt) {
    case "bottom" : 
        return /* Bottom */0;
    case "pane" : 
        return /* Pane */1;
    default:
      return /* Nowhere */2;
  }
}

var mountingPosition = /* record */Block.record(["contents"], [2]);

function mountPanel(jsMountAt) {
  translateJSMountAt(jsMountAt);
  return /* () */0;
}

function renderPanel(param) {
  console.log("render panel");
  var element = document.createElement("article");
  element.classList.add("agda-mode");
  atom.workspace.addBottomPanel({
        item: element,
        visible: true
      });
  ReactDom.render(ReasonReact.element(undefined, undefined, Panel$AgdaMode.make((function (handle) {
                  updateHeader[0] = handle;
                  return /* () */0;
                }), (function (handle) {
                  updateEmacsBody[0] = handle;
                  return /* () */0;
                }), (function (handle) {
                  updateJSONBody[0] = handle;
                  return /* () */0;
                }), /* array */[])), element);
  return /* () */0;
}

function initialize(param) {
  return renderPanel(/* () */0);
}

function jsUpdateEmacsBody(raw) {
  return Curry._1(updateEmacsBody[0], /* record */Block.record([
                "kind",
                "header",
                "body"
              ], [
                raw.kind,
                raw.header,
                raw.body
              ]));
}

function jsUpdateJSONBody(raw) {
  return Curry._1(updateJSONBody[0], /* record */Block.record([
                "kind",
                "rawJSON",
                "rawString"
              ], [
                raw.kind,
                raw.rawJSON,
                raw.rawString
              ]));
}

function jsUpdateHeader(raw) {
  return Curry._1(updateHeader[0], /* record */Block.record([
                "text",
                "style"
              ], [
                raw.text,
                raw.style
              ]));
}

exports.updateEmacsBody = updateEmacsBody;
exports.updateJSONBody = updateJSONBody;
exports.updateHeader = updateHeader;
exports.translateJSMountAt = translateJSMountAt;
exports.mountingPosition = mountingPosition;
exports.mountPanel = mountPanel;
exports.renderPanel = renderPanel;
exports.initialize = initialize;
exports.jsUpdateEmacsBody = jsUpdateEmacsBody;
exports.jsUpdateJSONBody = jsUpdateJSONBody;
exports.jsUpdateHeader = jsUpdateHeader;
/* react-dom Not a pure module */
