// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Mocha$BsMocha = require("bs-mocha/lib/js/src/Mocha.bs.js");
var Assert$BsMocha = require("bs-mocha/lib/js/src/Assert.bs.js");
var Promise$BsMocha = require("bs-mocha/lib/js/src/Promise.bs.js");
var Response$AgdaMode = require("../../src/Response.bs.js");
var Test__Util$AgdaMode = require("../Test__Util.bs.js");
var Test__Parser__SExpression$AgdaMode = require("./Test__Parser__SExpression.bs.js");

function toResponses(exprs) {
  var result = Rebase.$$Array[/* map */0](Response$AgdaMode.parse, exprs);
  var extractError = function (param) {
    if (param.tag) {
      return Caml_option.some(param[0]);
    }
    
  };
  var extractOk = Rebase.$$Option[/* fromResult */12];
  var failures = Rebase.$$Array[/* filterMap */23](extractError, result);
  Rebase.$$Array[/* forEach */8](Assert$BsMocha.fail, failures);
  return Rebase.$$Array[/* filterMap */23](extractOk, result);
}

Mocha$BsMocha.describe("when parsing responses")(undefined, undefined, undefined, (function (param) {
        return Rebase.$$Array[/* forEach */8]((function (filepath) {
                      return Promise$BsMocha.it("should golden test " + filepath)(undefined, undefined, undefined, (function (param) {
                                    var partial_arg = /* array */[];
                                    var partial_arg$1 = Curry._2(Rebase.Fn[/* >> */6], Curry._2(Rebase.Fn[/* >> */6], (function (param) {
                                                return Test__Parser__SExpression$AgdaMode.parseSExpression(partial_arg, param);
                                              }), toResponses), Test__Util$AgdaMode.serializeWith(Response$AgdaMode.toString));
                                    var partial_arg$2 = Test__Util$AgdaMode.Golden[/* map */1];
                                    var partial_arg$3 = Curry._2(Rebase.Fn[/* >> */6], (function (param) {
                                            return partial_arg$2(partial_arg$1, param);
                                          }), Test__Util$AgdaMode.Golden[/* compare */3]);
                                    return Test__Util$AgdaMode.Golden[/* readFile */2](filepath).then(Curry.__1(partial_arg$3));
                                  }));
                    }), Test__Util$AgdaMode.getGoldenFilepathsSync("test/Parser/Response"));
      }));

exports.toResponses = toResponses;
/*  Not a pure module */
