// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Async$BsMocha = require("bs-mocha/lib/js/src/Async.bs.js");
var Mocha$BsMocha = require("bs-mocha/lib/js/src/Mocha.bs.js");
var Assert$BsMocha = require("bs-mocha/lib/js/src/Assert.bs.js");
var Promise$BsMocha = require("bs-mocha/lib/js/src/Promise.bs.js");
var Test__Util$AgdaMode = require("./Test__Util.bs.js");

Mocha$BsMocha.describe_only("Input Method")(undefined, undefined, undefined, (function (param) {
        Promise$BsMocha.before(undefined)(undefined, undefined, undefined, Test__Util$AgdaMode.Package[/* activate */2]);
        Promise$BsMocha.after(undefined)(undefined, undefined, undefined, Test__Util$AgdaMode.Package[/* deactivate */3]);
        Promise$BsMocha.it("should not add class '.agda-mode-input-method-activated' to the editor element before triggering")(undefined, undefined, undefined, (function (param) {
                return Curry._1(Test__Util$AgdaMode.$$File[/* openAsset */1], "Blank1.agda").then((function (param) {
                                return Test__Util$AgdaMode.dispatch("agda-mode:load", param);
                              })).then((function (editor) {
                              var element = atom.views.getView(editor);
                              Assert$BsMocha.equal(undefined, false, element.classList.contains("agda-mode-input-method-activated"));
                              return Promise.resolve(/* () */0);
                            }));
              }));
        return Async$BsMocha.it("should add class '.agda-mode-input-method-activated' to the editor element after triggering")(undefined, undefined, undefined, (function (done_) {
                      Curry._1(Test__Util$AgdaMode.$$File[/* openAsset */1], "Blank1.agda").then((function (param) {
                                return Test__Util$AgdaMode.dispatch("agda-mode:load", param);
                              })).then((function (editor) {
                              var element = atom.views.getView(editor);
                              var press = function (key) {
                                return atom.keymaps.constructor.buildKeydownEvent(key, {
                                            ctrl: false,
                                            alt: false,
                                            shift: false,
                                            cmd: false,
                                            which: 0,
                                            target: element
                                          });
                              };
                              atom.keymaps.handleKeyboardEvent(press("\\"));
                              setTimeout((function (param) {
                                      console.log(element.classList.contains("agda-mode-input-method-activated"));
                                      return Curry._2(done_, undefined, /* () */0);
                                    }), 1000);
                              return Promise.resolve(/* () */0);
                            }));
                      return /* () */0;
                    }));
      }));

/*  Not a pure module */
