// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Os = require("os");
var Curry = require("bs-platform/lib/js/curry.js");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.js");
var Log$AgdaMode = require("./Log.bs.js");
var Util$AgdaMode = require("./Util/Util.bs.js");
var Event$AgdaMode = require("./Util/Event.bs.js");
var Parser$AgdaMode = require("./Parser.bs.js");
var Process$AgdaMode = require("./Process.bs.js");
var Response$AgdaMode = require("./Response.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function toString(param) {
  switch (param.tag | 0) {
    case /* PathSearch */0 :
        return Curry._1(Process$AgdaMode.PathSearch.$$Error.toString, param[0]);
    case /* Validation */1 :
        return Curry._1(Process$AgdaMode.Validation.$$Error.toString, param[0]);
    case /* Process */2 :
        return Process$AgdaMode.$$Error.toString(param[0]);
    
  }
}

var $$Error = {
  toString: toString
};

function toString$1(param) {
  if (param) {
    return "Emacs / JSON";
  } else {
    return "Emacs";
  }
}

var Protocol = {
  toString: toString$1
};

function serialize(self) {
  var path = "* path: " + self[/* path */0];
  var args = "* args: " + Util$AgdaMode.Pretty.array(self[/* args */1]);
  var version = "* version: " + self[/* version */2];
  var protocol = "* protocol: " + (
    self[/* protocol */3] ? "Emacs / JSON" : "Emacs"
  );
  var os = "* platform: " + Os.type();
  return "## Parse Log\n" + (String(path) + ("\n" + (String(args) + ("\n" + (String(version) + ("\n" + (String(protocol) + ("\n" + (String(os) + "\n  ")))))))));
}

var Metadata = {
  Protocol: Protocol,
  serialize: serialize
};

function disconnect(error, self) {
  Curry._1(self[/* process */1][/* disconnect */2], /* () */0);
  Rebase.List.forEach((function (ev) {
          return Curry._1(ev[/* emit */1], /* Error */Caml_chrome_debugger.variant("Error", 1, [error]));
        }), self[/* queue */2]);
  self[/* queue */2] = /* [] */0;
  self[/* encountedFirstPrompt */4] = false;
  self[/* log */5] = /* array */[];
  return /* () */0;
}

function autoSearch(name) {
  return $$Promise.mapError(Process$AgdaMode.PathSearch.run(name), (function (e) {
                return /* PathSearch */Caml_chrome_debugger.variant("PathSearch", 0, [e]);
              }));
}

function validateAndMake(pathAndParams) {
  var validator = function (output) {
    var match = output.match((/Agda version (.*)/));
    if (match !== null) {
      var match$1 = Rebase.$$Array.get(match, 1);
      if (match$1 !== undefined) {
        var match$2 = (/--interaction-json/).test(output);
        return /* Ok */Caml_chrome_debugger.variant("Ok", 0, [/* tuple */[
                    match$1,
                    match$2 ? /* EmacsAndJSON */1 : /* EmacsOnly */0
                  ]]);
      } else {
        return /* Error */Caml_chrome_debugger.variant("Error", 1, ["Cannot read Agda version"]);
      }
    } else {
      return /* Error */Caml_chrome_debugger.variant("Error", 1, ["Cannot read Agda version"]);
    }
  };
  var match = Parser$AgdaMode.commandLine(pathAndParams);
  var args = match[1];
  var path = match[0];
  return $$Promise.mapError($$Promise.mapOk(Process$AgdaMode.Validation.run(path + " -V", validator), (function (param) {
                    return /* record */Caml_chrome_debugger.record([
                              "path",
                              "args",
                              "version",
                              "protocol"
                            ], [
                              path,
                              args,
                              param[0],
                              param[1]
                            ]);
                  })), (function (e) {
                return /* Validation */Caml_chrome_debugger.variant("Validation", 1, [e]);
              }));
}

function connect(metadata) {
  var args = Rebase.$$Array.concat(metadata[/* args */1], /* array */["--interaction"]);
  var $$process = Process$AgdaMode.make(metadata[/* path */0], args);
  return /* record */Caml_chrome_debugger.record([
            "metadata",
            "process",
            "queue",
            "resetLogOnLoad",
            "encountedFirstPrompt",
            "log"
          ], [
            metadata,
            $$process,
            0,
            true,
            false,
            []
          ]);
}

function wire(self) {
  var partial_arg = Rebase.Result.forEach;
  var logSExpression = Curry._1(Parser$AgdaMode.Incr.$$Event.tap, (function (param) {
          return partial_arg((function (expr) {
                        return Log$AgdaMode.logSExpression(expr)(self[/* log */5]);
                      }), param);
        }));
  var toResponse = Curry._1(Parser$AgdaMode.Incr.$$Event.flatMap, (function (param) {
          if (param.tag) {
            return /* Yield */Caml_chrome_debugger.simpleVariant("Yield", [/* Error */Caml_chrome_debugger.variant("Error", 1, [param[0]])]);
          } else {
            var tokens = param[0];
            if (tokens.tag || tokens[0] !== "Agda2>") {
              return /* Yield */Caml_chrome_debugger.simpleVariant("Yield", [Response$AgdaMode.parse(tokens)]);
            } else {
              return /* Stop */0;
            }
          }
        }));
  var partial_arg$1 = Rebase.Result.forEach;
  var logResponse = Curry._1(Parser$AgdaMode.Incr.$$Event.tap, (function (param) {
          return partial_arg$1((function (expr) {
                        return Log$AgdaMode.logResponse(expr)(self[/* log */5]);
                      }), param);
        }));
  var handleResponse = function (res) {
    var match = self[/* queue */2];
    if (match) {
      var req = match[0];
      if (res) {
        return Curry._1(req[/* emit */1], /* Ok */Caml_chrome_debugger.variant("Ok", 0, [/* Yield */Caml_chrome_debugger.simpleVariant("Yield", [res[0]])]));
      } else if (self[/* encountedFirstPrompt */4]) {
        Curry._1(req[/* emit */1], /* Ok */Caml_chrome_debugger.variant("Ok", 0, [/* Stop */0]));
        self[/* queue */2] = match[1];
        Curry._1(req[/* destroy */4], /* () */0);
        return /* () */0;
      } else {
        self[/* encountedFirstPrompt */4] = true;
        return /* () */0;
      }
    } else {
      return /* () */0;
    }
  };
  var pipeline = Parser$AgdaMode.SExpression.makeIncr(Curry._2(Rebase.Fn.$great$great, Curry._2(Rebase.Fn.$great$great, Curry._2(Rebase.Fn.$great$great, logSExpression, toResponse), logResponse), handleResponse));
  var onData = function (param) {
    if (param.tag) {
      var e = param[0];
      Rebase.List.forEach((function (req) {
              Curry._1(req[/* emit */1], /* Error */Caml_chrome_debugger.variant("Error", 1, [e]));
              return Curry._1(req[/* destroy */4], /* () */0);
            }), self[/* queue */2]);
      self[/* queue */2] = /* [] */0;
      return /* () */0;
    } else {
      var rawText = param[0];
      Log$AgdaMode.logRawText(rawText)(self[/* log */5]);
      var partial_arg = Parser$AgdaMode.Incr.feed;
      return Rebase.$$Array.forEach((function (param) {
                    return partial_arg(pipeline, param);
                  }), Curry._1(Parser$AgdaMode.split, rawText));
    }
  };
  Curry._1(self[/* process */1][/* emitter */1][/* on */3], onData);
  return self;
}

function send(request, self) {
  var reqEvent = Event$AgdaMode.make(/* () */0);
  self[/* queue */2] = /* :: */Caml_chrome_debugger.simpleVariant("::", [
      reqEvent,
      self[/* queue */2]
    ]);
  Curry._1(self[/* process */1][/* send */0], request);
  return reqEvent;
}

function resetLog(self) {
  self[/* log */5] = /* array */[];
  return /* () */0;
}

function dump(self) {
  var serialize$1 = function (self) {
    var metadata = serialize(self[/* metadata */0]);
    var log = Curry._1(Log$AgdaMode.serialize, self[/* log */5]);
    return metadata + ("\n" + (log + "\n"));
  };
  var text = serialize$1(self);
  var itemOptions = {
    initialLine: 0,
    initialColumn: 0,
    split: "left",
    activatePane: true,
    activateItem: true,
    pending: false,
    searchAllPanes: true,
    location: undefined
  };
  $$Promise.map($$Promise.Js.toResult($$Promise.Js.fromBsPromise(atom.workspace.open("agda-mode://log.md", itemOptions))), (function (param) {
          if (param.tag) {
            return /* () */0;
          } else {
            param[0].insertText(text);
            return /* () */0;
          }
        }));
  return /* () */0;
}

exports.$$Error = $$Error;
exports.Metadata = Metadata;
exports.disconnect = disconnect;
exports.autoSearch = autoSearch;
exports.validateAndMake = validateAndMake;
exports.connect = connect;
exports.wire = wire;
exports.send = send;
exports.resetLog = resetLog;
exports.dump = dump;
/* os Not a pure module */
