// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Util$AgdaMode = require("../../Util.bs.js");
var Buffer$AgdaMode = require("../Panel/InputMethod/Buffer.bs.js");

function Settings__Debug(Props) {
  var debug = Props.debug;
  var hidden = Props.hidden;
  var className = Curry._1(Util$AgdaMode.ClassName[/* serialize */2], Util$AgdaMode.ClassName[/* addWhen */1]("hidden", hidden, /* :: */Block.simpleVariant("::", [
              "agda-settings-debug",
              /* [] */0
            ])));
  console.log(debug[/* inputMethod */0]);
  var match = debug[/* inputMethod */0][/* activated */0];
  return React.createElement("section", {
              className: className
            }, React.createElement("h1", undefined, React.createElement("span", {
                      className: "icon icon-terminal"
                    }), React.createElement("span", undefined, "Debug")), React.createElement("hr", undefined), React.createElement("p", undefined, "only available in dev mode"), React.createElement("h2", undefined, React.createElement("span", undefined, "Input Method"), match ? React.createElement("span", {
                        className: "icon icon-primitive-dot text-success",
                        id: "input-method-activation",
                        title: "activated"
                      }) : React.createElement("span", {
                        className: "icon icon-primitive-dot text-error",
                        id: "input-method-activation",
                        title: "deactivated"
                      })), React.createElement("p", undefined, "input sequence : ", React.createElement("span", {
                      className: "inline-block highlight"
                    }, Buffer$AgdaMode.toSequence(debug[/* inputMethod */0][/* buffer */2])), React.createElement("br", undefined), "output buffer : ", React.createElement("span", {
                      className: "inline-block highlight"
                    }, Buffer$AgdaMode.toSurface(debug[/* inputMethod */0][/* buffer */2]))));
}

var make = Settings__Debug;

exports.make = make;
/* react Not a pure module */
