// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Util$AgdaMode = require("../../Util/Util.bs.js");
var Buffer$AgdaMode = require("../Panel/InputMethod/Buffer.bs.js");

function Settings__Debug(Props) {
  var debug = Props.debug;
  var hidden = Props.hidden;
  var inputMethod = debug[/* inputMethod */0];
  var match = inputMethod[/* activated */0];
  return React.createElement("section", {
              className: "agda-settings-debug" + Util$AgdaMode.React.showWhen(!hidden)
            }, React.createElement("h1", undefined, React.createElement("span", {
                      className: "icon icon-terminal"
                    }), React.createElement("span", undefined, "Debug")), React.createElement("p", undefined, "only available in dev mode"), React.createElement("hr", undefined), React.createElement("h2", undefined, React.createElement("span", undefined, "Input Method"), match ? React.createElement("span", {
                        className: "icon icon-primitive-dot text-success",
                        id: "input-method-activation",
                        title: "activated"
                      }) : React.createElement("span", {
                        className: "icon icon-primitive-dot text-error",
                        id: "input-method-activation",
                        title: "deactivated"
                      })), React.createElement("p", undefined, "input sequence : ", React.createElement("span", {
                      className: "inline-block highlight"
                    }, Buffer$AgdaMode.toSequence(inputMethod[/* buffer */2]))), React.createElement("p", undefined, "output buffer : ", React.createElement("span", {
                      className: "inline-block highlight"
                    }, Buffer$AgdaMode.toSurface(inputMethod[/* buffer */2]))), React.createElement("p", undefined, "# of markers : ", React.createElement("span", {
                      className: "inline-block highlight"
                    }, String(Rebase.$$Array.length(inputMethod[/* markers */1])))), React.createElement("div", {
                  className: "block"
                }, React.createElement("button", {
                      className: "btn",
                      onClick: (function (param) {
                          console.log(inputMethod[/* markers */1]);
                          return /* () */0;
                        })
                    }, "Dump Markers")));
}

var make = Settings__Debug;

exports.make = make;
/* react Not a pure module */
