// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Settings__Breadcrumb(Props) {
  var uri = Props.uri;
  var onNavigate = Props.onNavigate;
  var tmp;
  switch (uri) {
    case /* Root */0 :
        tmp = null;
        break;
    case /* Connection */1 :
        tmp = React.createElement("li", undefined, React.createElement("a", {
                  href: "#"
                }, React.createElement("span", {
                      className: "icon icon-plug"
                    }, "Connection")));
        break;
    case /* Log */2 :
        tmp = React.createElement("li", undefined, React.createElement("a", {
                  href: "#"
                }, React.createElement("span", {
                      className: "icon icon-comment-discussion"
                    }, "Log")));
        break;
    case /* InputMethod */3 :
        tmp = React.createElement("li", undefined, React.createElement("a", {
                  href: "#"
                }, React.createElement("span", {
                      className: "icon icon-keyboard"
                    }, "Input Method")));
        break;
    case /* Debug */4 :
        tmp = React.createElement("li", undefined, React.createElement("a", {
                  href: "#"
                }, React.createElement("span", {
                      className: "icon icon-terminal"
                    }, "Debug")));
        break;
    
  }
  return React.createElement("nav", {
              className: "agda-settings-breadcrumb"
            }, React.createElement("ol", {
                  className: "breadcrumb"
                }, React.createElement("li", undefined, React.createElement("a", {
                          href: "#",
                          onClick: (function (param) {
                              return Curry._1(onNavigate, /* Root */0);
                            })
                        }, React.createElement("span", {
                              className: "icon icon-settings"
                            }, "Settings"))), tmp));
}

var make = Settings__Breadcrumb;

exports.make = make;
/* react Not a pure module */
