// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Util$AgdaMode = require("../../Util.bs.js");
var Caml_chrome_debugger = require("bs-platform/lib/js/caml_chrome_debugger.js");

function Settings__Placeholder(Props) {
  var hidden = Props.hidden;
  var className = Curry._1(Util$AgdaMode.ClassName[/* serialize */2], Util$AgdaMode.ClassName[/* addWhen */1]("hidden", hidden, /* :: */Caml_chrome_debugger.simpleVariant("::", [
              "agda-settings-placeholder",
              /* [] */0
            ])));
  return React.createElement("section", {
              className: className
            }, React.createElement("h1", undefined, React.createElement("span", undefined, "Coming soon")));
}

var make = Settings__Placeholder;

exports.make = make;
/* react Not a pure module */
