// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Exception = Caml_exceptions.create("N-AgdaMode.Exception");

var OS = /* alias */0;

var Util = /* alias */0;

var Fs = /* alias */0;

exports.Exception = Exception;
exports.OS = OS;
exports.Util = Util;
exports.Fs = Fs;
/* No side effect */
