// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Emacs__Body$AgdaMode = require("../Emacs/Emacs__Body.bs.js");

function Body(Props) {
  var body = Props.body;
  var hidden = Props.hidden;
  var comp;
  comp = typeof body === "number" || body.tag ? null : React.createElement(Emacs__Body$AgdaMode.make, {
          data: body[0]
        });
  var className = hidden ? Rebase.$$String[/* joinWith */11](" ", /* :: */Block.simpleVariant("::", [
            "agda-body",
            /* :: */Block.simpleVariant("::", [
                "native-key-bindings",
                /* :: */Block.simpleVariant("::", [
                    "hidden",
                    /* [] */0
                  ])
              ])
          ])) : Rebase.$$String[/* joinWith */11](" ", /* :: */Block.simpleVariant("::", [
            "agda-body",
            /* :: */Block.simpleVariant("::", [
                "native-key-bindings",
                /* [] */0
              ])
          ]));
  return React.createElement("section", {
              className: className,
              tabIndex: -1
            }, comp);
}

var make = Body;

exports.make = make;
/* react Not a pure module */
