// Generated by BUCKLESCRIPT VERSION 5.0.1, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Emacs__Parser$AgdaMode = require("./Emacs__Parser.bs.js");
var Emacs__Component$AgdaMode = require("./Emacs__Component.bs.js");

var component = ReasonReact.statelessComponent("EmacsGoalTypeContext");

function make(body, _children) {
  return /* record */Block.record([
            "debugName",
            "reactClassInternal",
            "handedOffState",
            "willReceiveProps",
            "didMount",
            "didUpdate",
            "willUnmount",
            "willUpdate",
            "shouldUpdate",
            "render",
            "initialState",
            "retainedProps",
            "reducer",
            "jsElementWrapped"
          ], [
            component[/* debugName */0],
            component[/* reactClassInternal */1],
            component[/* handedOffState */2],
            component[/* willReceiveProps */3],
            component[/* didMount */4],
            component[/* didUpdate */5],
            component[/* willUnmount */6],
            component[/* willUpdate */7],
            component[/* shouldUpdate */8],
            (function (_self) {
                var parsed = Emacs__Parser$AgdaMode.$$Response[/* goalTypeContext */2](body);
                return React.createElement(React.Fragment, undefined, React.createElement("ul", undefined, Rebase.$$Option[/* mapOr */18]((function (param) {
                                      return ReasonReact.element(undefined, undefined, Emacs__Component$AgdaMode.Labeled[/* make */1]("Goal ", param[0], /* array */[]));
                                    }), null, parsed[/* goal */0]), Rebase.$$Option[/* mapOr */18]((function (param) {
                                      return ReasonReact.element(undefined, undefined, Emacs__Component$AgdaMode.Labeled[/* make */1]("Have ", param[0], /* array */[]));
                                    }), null, parsed[/* have */1])), ReactDOMRe.createElementVariadic("ul", undefined, Rebase.$$Array[/* map */0]((function (value) {
                                      return ReasonReact.element(undefined, undefined, Emacs__Component$AgdaMode.Output[/* make */1](value, /* array */[]));
                                    }), parsed[/* interactionMetas */2])), ReactDOMRe.createElementVariadic("ul", undefined, Rebase.$$Array[/* map */0]((function (value) {
                                      return ReasonReact.element(undefined, undefined, Emacs__Component$AgdaMode.Output[/* make */1](value, /* array */[]));
                                    }), parsed[/* hiddenMetas */3])));
              }),
            component[/* initialState */10],
            component[/* retainedProps */11],
            component[/* reducer */12],
            component[/* jsElementWrapped */13]
          ]);
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
