// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Rebase = require("@glennsl/rebase/lib/js/src/Rebase.bs.js");
var Util$AgdaMode = require("../../Util/Util.bs.js");
var Emacs__Parser$AgdaMode = require("./Emacs__Parser.bs.js");
var Emacs__Component$AgdaMode = require("./Emacs__Component.bs.js");

function parse(raw) {
  var lines = Emacs__Parser$AgdaMode.unindent(raw.split("\n"));
  return Rebase.$$Array.filterMap((function (x) {
                return x;
              }), Rebase.$$Array.map(Emacs__Component$AgdaMode.Output.parse, lines));
}

function Emacs__Context(Props) {
  var body = Props.body;
  return Util$AgdaMode.React.manyIn(Rebase.$$Array.map((function (value) {
                    return React.createElement(Emacs__Component$AgdaMode.Output.make, {
                                value: value
                              });
                  }), parse(body)), "ul");
}

var make = Emacs__Context;

exports.parse = parse;
exports.make = make;
/* react Not a pure module */
