// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Component = /* alias */0;

var Parser = /* alias */0;

var AllGoalsWarnings = /* alias */0;

exports.Component = Component;
exports.Parser = Parser;
exports.AllGoalsWarnings = AllGoalsWarnings;
/* No side effect */
